### ISSUE TITLE
Rename builder artifact

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff-buildpack-group#6]
We should rename `projectriff/buildpack` to `projectriff/build` to be less confusing and also consistent with `pack/build`

**Comment by ericbottard** [comment]
I would argue that the word `build` in `pack/build` and in our builder don't have the same meaning.
`projectriff/builder` is a better choice IMHO

**Comment by trisberg** [comment]
I'm OK with `projectriff/builder`
